---
version: "3.7"

volumes:
  photol-db-data:

services:
  photoldb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      POSTGRES_USER: photol
      POSTGRES_PASSWORD: photol
      POSTGRES_DB: photol
    volumes:
      - photol-db-data:/data/db
